---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: '13.0.113'
  # product_version: '13'
  # product_version: '14'
  install_strategy: once

client_rb:
  treat_deprecation_warnings_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux-2
    driver_config:
      box: ywatase/amzn2
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: config_1
    run_list:
      - recipe[test::config_1]
    includes: centos-7
  - name: default
    run_list:
      - recipe[haproxy_fail::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
